#���ݿ�
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
     username: buctcs1802
     password: cs1802..
#    username: root
#    password: cry900207.
    url: jdbc:mysql://localhost:3306/museum?autoReconnect=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  #����json�����ڸ�ʽ
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
#����mybatis
mybatis:
  type-aliases-package: com.cs1802.museum.bean
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #����ֵ�����շ�ӳ��
logging.level.com.cs1802.museum.mapper: debug
server:
  port: 81
